### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by counterfit** [chikorita157/hachidori#7]
I've noticed both Hachidori and MAL Updater have been crashing quietly. [Here's a report] (https://www.dropbox.com/s/heuklb91g1w6qnp/Hachidori_2015-06-26-011933_SilverSurfer.crash?dl=0).
I'll make another for MAL-U

**Comment by chikorita157** [comment]
It seems that there is an issue with the stream detection. Can you paste the console output and reproduce the issue? You can do this by opening Console.app and then filter for Hachidori

**Comment by chikorita157** [comment]
It has been a week, are you able to reproduce the bug and give me the terminal output by filtering Hachidori and give me the detectstream output as mentioned above.

**Comment by counterfit** [comment]
I just got this to happen again. This is happening with a remote Plex server/player, but it may have been influenced by the Plex Web player this time. [Crash report] (https://www.dropbox.com/s/z44z7xgxgnswa6t/Hachidori_2015-07-06-185757_SilverSurfer.crash?dl=0). [Console stuff immediately before the crash] (https://www.dropbox.com/s/ypywaz2uvrvb6uj/hachidori_crash_7_6_15.txt?dl=0).

**Comment by chikorita157** [comment]
Can you upload the screenshot of the plex web player browser window with the media playing. If you are running Yosemite, show the tab bar so I can see the title

**Comment by counterfit** [comment]
I just had another crash without Plex Web being involved at all. [Here's a folder] (https://www.dropbox.com/sh/c91g9ekssqib1ul/AADEG9eYsh40-vO5mahJ4CxNa?dl=0) with the relevant stuff for this and MAL Updater. It seems to be happening at the end of whatever was playing, or if Plex hasn't played anything for a little while, rather than during playback.

**Comment by chikorita157** [comment]
I probably figured out the issue. It seems that the ignore check for streams checks for directories when there aren't any. When the program tries to find a directory when there is none to get the path, it returns a nil string and then causes the program to crash.

I will try to reproduce this and then make the fix. Not so sure about plex, but I will look into that.

**Comment by chikorita157** [comment]
I tried to reproduce the issue and I'm not seeing it. Can you upload the preferences file. First logout of your account and then upload the preferences file. The file is moe.ateliershiori.Hachidori.plist and is located in ~/Library/Preferences

**Comment by counterfit** [comment]
[Preferences] (https://www.dropbox.com/s/ibsav54cbua3vti/moe.ateliershiori.Hachidori.plist?dl=0)

**Comment by chikorita157** [comment]
Try this version. I attempted to make a fix so that it won't check the directory if the value is nil. If you encounter any problems, give me the console output and crash log.
http://skitch.chikorita157.com/hachidori-1.1.6b1-zip

**Comment by chikorita157** [comment]
There is no response, so the issue is now closed.
