### ISSUE TITLE
Unable to login if password contains special characters

### ISSUE THREAD

**Issue by floatingdino** [chikorita157/hachidori#9]
When using a password containing '*' login is impossible

**Comment by chikorita157** [comment]
See if this build fixes the issue. I switched to JSON for the login API and my password has special characters and it works.

[hachidori-1.1.8b2.zip](https://github.com/chikorita157/hachidori/files/251166/hachidori-1.1.8b2.zip)

**Comment by chikorita157** [comment]
I have tested with a password containing a * and it works... Therefore, I will be releasing a new beta and it will be resolved with https://github.com/chikorita157/hachidori/commit/dd3b1091891e73fef088ad41dfb9a7f04e413544
